import type { AppLocale } from "./i18n-shared";

const teamFlagCodes: Record<string, string> = {
  Algeria: "dz",
  Argentina: "ar",
  Australia: "au",
  Austria: "at",
  Belgium: "be",
  "Bosnia and Herzegovina": "ba",
  Brazil: "br",
  "Cabo Verde": "cv",
  Canada: "ca",
  Colombia: "co",
  "Congo DR": "cd",
  "Côte d'Ivoire": "ci",
  Croatia: "hr",
  Curaçao: "cw",
  Czechia: "cz",
  Ecuador: "ec",
  Egypt: "eg",
  England: "gb-eng",
  France: "fr",
  Germany: "de",
  Ghana: "gh",
  Haiti: "ht",
  "IR Iran": "ir",
  Iraq: "iq",
  Japan: "jp",
  Jordan: "jo",
  "Korea Republic": "kr",
  Mexico: "mx",
  Morocco: "ma",
  Netherlands: "nl",
  "New Zealand": "nz",
  Norway: "no",
  Panama: "pa",
  Paraguay: "py",
  Portugal: "pt",
  Qatar: "qa",
  "Saudi Arabia": "sa",
  Scotland: "gb-sct",
  Senegal: "sn",
  "South Africa": "za",
  Spain: "es",
  Sweden: "se",
  Switzerland: "ch",
  Tunisia: "tn",
  Türkiye: "tr",
  Uruguay: "uy",
  USA: "us",
  Uzbekistan: "uz",
};

const teamDisplayNames: Partial<Record<AppLocale, Record<string, string>>> = {
  "pt-BR": {
    Algeria: "Argelia",
    Argentina: "Argentina",
    Australia: "Australia",
    Austria: "Austria",
    Belgium: "Belgica",
    "Bosnia and Herzegovina": "Bosnia e Herzegovina",
    Brazil: "Brasil",
    "Cabo Verde": "Cabo Verde",
    Canada: "Canada",
    Colombia: "Colombia",
    "Congo DR": "RD Congo",
    Croatia: "Croacia",
    Czechia: "Tchequia",
    Ecuador: "Equador",
    Egypt: "Egito",
    England: "Inglaterra",
    France: "Franca",
    Germany: "Alemanha",
    Ghana: "Gana",
    Haiti: "Haiti",
    "IR Iran": "Ira",
    Iraq: "Iraque",
    Japan: "Japao",
    Jordan: "Jordania",
    "Korea Republic": "Coreia do Sul",
    Mexico: "Mexico",
    Morocco: "Marrocos",
    Netherlands: "Holanda",
    "New Zealand": "Nova Zelandia",
    Norway: "Noruega",
    Panama: "Panama",
    Paraguay: "Paraguai",
    Portugal: "Portugal",
    Qatar: "Catar",
    "Saudi Arabia": "Arabia Saudita",
    Scotland: "Escocia",
    Senegal: "Senegal",
    "South Africa": "Africa do Sul",
    Spain: "Espanha",
    Sweden: "Suecia",
    Switzerland: "Suica",
    Tunisia: "Tunisia",
    Uruguay: "Uruguai",
    USA: "Estados Unidos",
    Uzbekistan: "Uzbequistao",
  },
  "es-ES": {
    Algeria: "Argelia",
    Australia: "Australia",
    Austria: "Austria",
    Belgium: "Belgica",
    "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    Brazil: "Brasil",
    Canada: "Canada",
    Colombia: "Colombia",
    "Congo DR": "RD Congo",
    Croatia: "Croacia",
    Czechia: "Chequia",
    Ecuador: "Ecuador",
    Egypt: "Egipto",
    England: "Inglaterra",
    France: "Francia",
    Germany: "Alemania",
    Ghana: "Ghana",
    "IR Iran": "Iran",
    Iraq: "Irak",
    Japan: "Japon",
    Jordan: "Jordania",
    "Korea Republic": "Corea del Sur",
    Mexico: "Mexico",
    Morocco: "Marruecos",
    Netherlands: "Paises Bajos",
    "New Zealand": "Nueva Zelanda",
    Norway: "Noruega",
    Paraguay: "Paraguay",
    Qatar: "Catar",
    "Saudi Arabia": "Arabia Saudita",
    Scotland: "Escocia",
    "South Africa": "Sudafrica",
    Spain: "Espana",
    Sweden: "Suecia",
    Switzerland: "Suiza",
    Tunisia: "Tunez",
    Uruguay: "Uruguay",
    USA: "Estados Unidos",
    Uzbekistan: "Uzbekistan",
  },
};

export function getTeamFlagUrl(team: string) {
  const code = teamFlagCodes[team];
  return code ? `https://flagcdn.com/${code}.svg` : null;
}

export function getTeamDisplayName(team: string, locale: AppLocale = "pt-BR") {
  return teamDisplayNames[locale]?.[team] ?? team;
}
