const venuesByMatch = new Map<string, string>([
  ["A::Mexico::South Africa", "Estádio Azteca"],
  ["A::Korea Republic::Czechia", "Estádio Akron"],
  ["B::Canada::Bosnia and Herzegovina", "Toronto"],
  ["D::USA::Paraguay", "Los Angeles"],
  ["B::Qatar::Switzerland", "São Francisco Bay Area"],
  ["C::Brazil::Morocco", "Nova York/Nova Jersey"],
  ["C::Haiti::Scotland", "Boston"],
  ["D::Australia::Türkiye", "Vancouver"],
  ["E::Germany::Curaçao", "Houston"],
  ["F::Netherlands::Japan", "Dallas"],
  ["E::Côte d'Ivoire::Ecuador", "Filadélfia"],
  ["F::Sweden::Tunisia", "Monterrey"],
  ["H::Spain::Cabo Verde", "Atlanta"],
  ["G::Belgium::Egypt", "Seattle"],
  ["H::Saudi Arabia::Uruguay", "Miami"],
  ["G::IR Iran::New Zealand", "Los Angeles"],
  ["I::France::Senegal", "Nova York/Nova Jersey"],
  ["I::Iraq::Norway", "Boston"],
  ["J::Argentina::Algeria", "Kansas City"],
  ["J::Austria::Jordan", "São Francisco Bay Area"],
  ["K::Portugal::Congo DR", "Houston"],
  ["L::England::Croatia", "Dallas"],
  ["L::Ghana::Panama", "Toronto"],
  ["K::Uzbekistan::Colombia", "Estádio Azteca"],
  ["A::Czechia::South Africa", "Atlanta"],
  ["B::Switzerland::Bosnia and Herzegovina", "Los Angeles"],
  ["B::Canada::Qatar", "Vancouver"],
  ["A::Mexico::Korea Republic", "Estádio Akron"],
  ["D::USA::Australia", "Seattle"],
  ["C::Scotland::Morocco", "Boston"],
  ["C::Brazil::Haiti", "Filadélfia"],
  ["D::Türkiye::Paraguay", "São Francisco Bay Area"],
  ["F::Netherlands::Sweden", "Houston"],
  ["E::Germany::Côte d'Ivoire", "Toronto"],
  ["E::Ecuador::Curaçao", "Kansas City"],
  ["F::Tunisia::Japan", "Monterrey"],
  ["H::Spain::Saudi Arabia", "Atlanta"],
  ["G::Belgium::IR Iran", "Seattle"],
  ["H::Uruguay::Cabo Verde", "Miami"],
  ["G::New Zealand::Egypt", "Vancouver"],
  ["J::Argentina::Austria", "Kansas City"],
  ["I::France::Iraq", "Nova York/Nova Jersey"],
  ["I::Norway::Senegal", "Boston"],
  ["J::Jordan::Algeria", "São Francisco Bay Area"],
  ["K::Portugal::Uzbekistan", "Houston"],
  ["L::England::Ghana", "Dallas"],
  ["L::Panama::Croatia", "Toronto"],
  ["K::Colombia::Congo DR", "Estádio Azteca"],
  ["B::Switzerland::Canada", "Vancouver"],
  ["B::Bosnia and Herzegovina::Qatar", "Seattle"],
  ["C::Morocco::Haiti", "Boston"],
  ["C::Scotland::Brazil", "Filadélfia"],
  ["A::South Africa::Korea Republic", "Monterrey"],
  ["A::Czechia::Mexico", "Estádio Azteca"],
  ["E::Ecuador::Germany", "Nova York/Nova Jersey"],
  ["E::Curaçao::Côte d'Ivoire", "Filadélfia"],
  ["F::Tunisia::Netherlands", "Kansas City"],
  ["F::Japan::Sweden", "Dallas"],
  ["D::Türkiye::USA", "Los Angeles"],
  ["D::Paraguay::Australia", "São Francisco Bay Area"],
  ["I::Senegal::Iraq", "Toronto"],
  ["I::Norway::France", "Boston"],
  ["H::Cabo Verde::Saudi Arabia", "Houston"],
  ["H::Uruguay::Spain", "Estádio Akron"],
  ["G::Egypt::IR Iran", "Seattle"],
  ["G::New Zealand::Belgium", "Vancouver"],
  ["L::Croatia::Ghana", "Filadélfia"],
  ["L::Panama::England", "Nova York/Nova Jersey"],
  ["K::Congo DR::Uzbekistan", "Atlanta"],
  ["K::Colombia::Portugal", "Miami"],
  ["J::Jordan::Argentina", "Dallas"],
  ["J::Algeria::Austria", "Kansas City"],
]);

function key(group: string, teamA: string, teamB: string) {
  return `${group}::${teamA}::${teamB}`;
}

export function getMatchVenue(group: string, teamA: string, teamB: string) {
  return venuesByMatch.get(key(group, teamA, teamB))
    ?? venuesByMatch.get(key(group, teamB, teamA))
    ?? "Local a confirmar";
}
