ALTER TABLE "Pool" ADD COLUMN "exactScorePoints" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Pool" ADD COLUMN "outcomePoints" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Pool" ADD COLUMN "mode" TEXT NOT NULL DEFAULT 'friends';
